create table domain_event_record (
    id bigint generated by default as identity primary key,
    event_key varchar(255) not null,
    biz_code varchar(128) not null,
    biz_id bigint null,
    event_type varchar(128) not null,
    handler_code varchar(128) not null,
    parent_handler_code varchar(128) null,
    payload clob not null,
    payload_version int not null,
    status varchar(64) not null,
    retry_num int not null,
    execute_time timestamp null,
    version bigint not null,
    created_at timestamp not null,
    updated_at timestamp not null
);

create unique index uk_domain_event_record_event_handler on domain_event_record (event_key, handler_code);
create index idx_domain_event_record_status_execute_id on domain_event_record (status, execute_time, id);
create index idx_domain_event_record_event_key_id on domain_event_record (event_key, id);
